//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaHesaplari.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HesapHareketleri
    {
        public int Id { get; set; }
        public int HesapId { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public decimal IslemTutari { get; set; }
        public string IslemTuru { get; set; }
    
        public virtual Hesaplar Hesaplar { get; set; }
    }
}
